### ISSUE TITLE
Custom css class for the context menu

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [jonataswalker/ol-contextmenu#47]
It would be great if you would integrate a possibility of setting a custom css class on the context menu. This is useful if you want to use different styled context menus on the map. I dont think that this is possible right now.

**Comment by jonataswalker** [comment]
Yeah, it's not possible right now. I'd like to add some themes and a way to add a custom one.

Meanwhile you can override it like:

```css
.ol-ctx-menu-container {
    background: #333 !important;
    color: #fff !important;
    font-size: 15px !important;
}
```
