### ISSUE TITLE
Many items in menu

### ISSUE THREAD

**Issue by rsobies** [jonataswalker/ol-contextmenu#49]
hi.
r you planning to make context menu with scrollbar when there are many items inside menu?
best regards

**Comment by jonataswalker** [comment]
Hey @rsobies this is really a thing I never thought about and it has to be done.

**Comment by jonataswalker** [comment]
Meanwhile you can use CSS to achieve this:

```css
.ol-ctx-menu-container {
    max-height: 200px;
    overflow-y: auto;
}
```
